modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="bloodborne"
version="0.0.1"
displayName="Bloodborne"
credits=""
authors="Floey"
description='''
A Minecraft mod
inspired by Bloodborne
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"